uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: '${{ secrets.GITHUB_TOKEN }}'
    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_X_BET_PROD_JD }}'
    channelId: live
    projectId: x-bet-prod-jd
    # Add this line:
    firebaseJsonPath: "./"
